# Generated by Django 3.2.7 on 2022-09-18 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loghistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_loghistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClicks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_link', models.TextField(blank=True, null=True)),
                ('date_clicked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_product_clicks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('search_data', models.TextField()),
                ('search_input', models.CharField(blank=True, max_length=100, null=True)),
                ('date_search', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('home_page', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_supplier',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shopscraper',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='TblGeneralInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_version', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.FileField(upload_to='rcstockv_logo/')),
                ('about', models.TextField(blank=True, null=True)),
                ('data_protection', models.TextField(blank=True, null=True)),
                ('affiliate', models.TextField(blank=True, null=True)),
                ('market_intelligence', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updatedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.authuser')),
            ],
            options={
                'db_table': 'tbl_general_info',
            },
        ),
    ]
