# Generated by Django 3.2.7 on 2022-10-03 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_searchlogs_tblmembershippricing_tblsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('date_search', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopPager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_page', models.CharField(max_length=255)),
                ('per_page_value', models.IntegerField(blank=True, null=True)),
                ('total_indicator_class', models.CharField(max_length=255)),
                ('total_indicator_type', models.CharField(max_length=255)),
                ('page_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_shop_pager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopScraperAdditional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('link_attribute', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('photo_attribute', models.CharField(max_length=255)),
                ('stock_status', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('wrapper', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_shop_scraper_additional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFaq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('isactive', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_faq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPriceDevelopment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_price_development',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSubPriceDevelopment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_sub_price_development',
                'managed': False,
            },
        ),
    ]
