# Generated by Django 4.2.18 on 2025-02-02 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_products_shoppager_shopscraperadditional_tblfaq_tblpricedevelopment_tblsubpricedevelopment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblContactUs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_seen', models.SmallIntegerField(blank=True, null=True)),
                ('is_reply', models.SmallIntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_contact_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblContactUsReply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('datetime_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_contact_us_reply',
                'managed': False,
            },
        ),
    ]
